apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: dedicated-admins-cluster
subjects:
- kind: Group
  name: dedicated-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dedicated-admins-cluster
