apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: #OPERATOR_NAME#
  namespace: #OPERATOR_NAMESPACE#
spec:
  channel: #CHANNEL#
  name: #OPERATOR_NAME#
  source: #IMAGE_NAME#
  sourceNamespace: #CATALOG_NAMESPACE#
